install! 'cocoapods', deterministic_uuids: false,
                      share_schemes_for_development_pods: false

use_frameworks!

abstract_target 'Vleteren' do
  pod 'Vleteren', :path => '../'

  target 'Vleteren_Example'

  target 'Vleteren_Tests' do
    inherit! :search_paths

    # This pod shouldn't be added here, but if not the spec classes are
    # unable to find the Vleteren module...
    pod 'Vleteren', :path => '../'

    # The test frameworks
    pod 'Quick',            '~> 0.10'
    pod 'Nimble',           '~> 5.0'
  end
end

post_install do |installer|
  # Make sure all targets have the right swift version set
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited) YES'
    end
  end
end
